#!/bin/sh

# Wallpaper:
eval `cat $HOME/.fehbg`

# Composite management:
xcompmgr &

# Keyboard repeat rate:
xset r rate 300 20

# Applications:
# autokey-gtk &
skype &
dropbox &
transmission-gtk --minimized &
(sleep 10 && qgmailnotifier) &

# Hack for fixing graphic card issue
sudo vgaswitch

exec awesome
# exec ck-launch-session gnome-session
# exec startkde
# exec startxfce4
# exec icewm
# exec openbox
# exec blackbox
# exec fluxbox
# exec ratpoison
# exec dwm
