#!/bin/sh

# Wallpaper:
eval `cat $HOME/.fehbg`

# Composite management:
xcompmgr &

# Keymaps:
xmodmap .Xmodmap

# Keyboard repeat rate:
xset r rate 300 20

# Applications:
skype &
nm-applet &
dropboxd &
#transmission-gtk --minimized &
#qgmailnotifier

if [ -d ~/Desktop ]; then
  rmdir ~/Desktop
fi

if [ -d ~/tmp ]; then
  rmdir ~/tmp
fi

exec awesome
# exec gnome-session
# exec startkde
# exec startxfce4
# exec icewm
# exec openbox
# exec blackbox
# exec fluxbox
# exec ratpoison
# exec dwm
