#!/bin/sh

# Wallpaper:
$HOME/bin/set-random-wallpaper $HOME/images/wallpapers
# $HOME/.fehbg &

# Keyboard backlight (set based on time of day)
$HOME/bin/keyboard-light-set

# Composite management:
xcompmgr &

# Keymaps and stuff:
# (loaded by lightdm)
# xmodmap .Xmodmap
# xrdb -merge .Xresources

# Keyboard repeat rate:
xset r rate 350 30

# Applications:
(sleep 2 && skypeforlinux) &
# pidgin &
nm-applet &
blueman-applet &
# blueberry-tray &
dropbox &
kbdd
# transmission-gtk --minimized &
# qgmailnotifier

# protonmail-bridge --no-window &

# Clipboard synchronization. (Problem? browser selection gets copied too. Issue when trying to paste over something)
# autocutsel -fork &
# autocutsel -selection PRIMARY -fork &

# fix cursor theme
xsetroot -cursor_name left_ptr&

# set up radeon video card fallback, run with:
# DRI_PRIME=1
xrandr --setprovideroffloadsink 1 0

# if [ -d ~/Desktop ]; then
#   rmdir ~/Desktop
# fi
#
# if [ -d ~/tmp ]; then
#   rmdir ~/tmp
# fi
